# Configuraci贸n general
title: R Curso de Probabilidad y Estadistica
description: Lugar donde esta el resultado de las clases
theme: hacker
url: https://julianvaldes24.github.io/R-Curso-Probabilidad-Estadistica/

# Configuraci贸n de navegaci贸n
header_pages:
  - about.md
  - contact.md
footer_pages:
  - privacy.md
  - terms.md

# Configuraci贸n de plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
